version: '3.3'

services:
  chatalart-server:
    image: chatalart-server
    container_name: chatalart-server
    hostname: chatalart-server
    depends_on:
      - chatalart-worker
      - kafka
    ports:
      - "10010:10010"

  chatalart-worker:
    image: chatalart-worker
    container_name: chatalart-worker
    hostname: chatalart-worker
    depends_on:
      - kafka
    ports:
      - "20010:20010"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock